package com.vibecheck.app.ui.screens

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.vibecheck.app.billing.PurchaseStatus
import com.vibecheck.app.domain.model.*
import com.vibecheck.app.localization.AppLocale
import com.vibecheck.app.release.ReleaseConfig
import com.vibecheck.app.ui.components.VibeActionSurface
import com.vibecheck.app.ui.theme.VibeColors

@Composable fun HomeScreen(isPremium:Boolean,premiumReady:Boolean,premiumPrice:String?,purchaseStatus:PurchaseStatus,selectedIntensity:GameIntensity,selectedPack:GamePack,savedPlayerCount:Int,groupLeaderName:String?,groupLeaderWins:Int,onOpenLeaderboard:()->Unit,onEditGroup:()->Unit,onOpenSettings:()->Unit,onPlaySolo:()->Unit,onBuyPremium:()->Unit,onIntensity:(GameIntensity)->Unit,onPack:(GamePack)->Unit,onMode:(GameMode)->Unit){
 var options by rememberSaveable{mutableStateOf(false)}
 LazyColumn(Modifier.fillMaxSize(),verticalArrangement=Arrangement.spacedBy(0.dp)){
  item{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween){Row(verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(8.dp)){Box(Modifier.size(9.dp).background(VibeColors.Green,CircleShape));Text("VIBECHECK",color=VibeColors.Purple,fontSize=13.sp,fontWeight=FontWeight.Black,letterSpacing=2.2.sp)};IconButton(onClick=onOpenSettings){Icon(Icons.Default.Settings,AppLocale.pick("Ouvrir les réglages","Open settings"),tint=VibeColors.TextSecondary)}}}
  item{Spacer(Modifier.height(8.dp));Text(AppLocale.pick("Qui connaît vraiment qui ?","Who really knows who?"),color=VibeColors.TextPrimary,style=MaterialTheme.typography.headlineLarge);Text(AppLocale.pick("Choisis comment tu veux jouer. Pas de compte, pas de prise de tête.","Choose how you want to play. No account, no hassle."),color=VibeColors.TextSecondary,style=MaterialTheme.typography.bodyLarge)}
  item{Spacer(Modifier.height(18.dp));PlayEntryCard(AppLocale.pick("Jouer ensemble","Play together"),if(savedPlayerCount>=2)AppLocale.pick("$savedPlayerCount joueurs mémorisés • configuration rapide","$savedPlayerCount saved players • quick setup") else AppLocale.pick("Passe le téléphone et compare les réponses","Pass the phone and compare answers"),Icons.Default.Groups,VibeColors.Purple,true){options=true};Spacer(Modifier.height(10.dp));PlayEntryCard(AppLocale.pick("Jouer en solo","Play solo"),AppLocale.pick("Tu participes, puis des personnalités publiques simulées répondent","You play first, then simulated public figures respond"),Icons.Default.Psychology,VibeColors.Rose,false,onPlaySolo)}
  if(savedPlayerCount>=2)item{Spacer(Modifier.height(10.dp));Card(colors=CardDefaults.cardColors(containerColor=VibeColors.Green.copy(alpha=.16f)),border=BorderStroke(1.dp,VibeColors.Green.copy(alpha=.32f)),shape=RoundedCornerShape(22.dp)){Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween){Text(AppLocale.pick("$savedPlayerCount joueurs mémorisés • groupe prêt","$savedPlayerCount saved players • group ready"),color=VibeColors.TextPrimary,fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f));TextButton(onClick=onEditGroup){Text(AppLocale.pick("Modifier","Edit"),fontWeight=FontWeight.Bold)}}};if(groupLeaderName!=null&&groupLeaderWins>0){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween){Text("Leader : $groupLeaderName • $groupLeaderWins victoire${if(groupLeaderWins==1)"" else "s"}",color=VibeColors.TextSecondary,fontSize=12.sp);TextButton(onClick=onOpenLeaderboard){Text(AppLocale.pick("Classement","Leaderboard"))}}}}
  if(ReleaseConfig.adRemovalPurchaseEnabled)item{Spacer(Modifier.height(12.dp));PremiumCard(isPremium,premiumReady,premiumPrice,purchaseStatus,onBuyPremium)}
  if(options){
   item{Spacer(Modifier.height(16.dp));SectionLabel("PACK");Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){GamePack.entries.forEach{p->ChoiceChip(p.title,p==selectedPack,VibeColors.Blue){onPack(p)}}};Text(selectedPack.subtitle,color=VibeColors.TextSecondary,fontSize=12.sp);Spacer(Modifier.height(12.dp));SectionLabel(AppLocale.pick("INTENSITÉ","INTENSITY"));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){GameIntensity.entries.forEach{i->ChoiceChip(i.title,i==selectedIntensity,VibeColors.Purple){onIntensity(i)}}};Text(selectedIntensity.subtitle,color=VibeColors.TextSecondary,fontSize=12.sp);Spacer(Modifier.height(14.dp));SectionLabel(AppLocale.pick("CHOISIS TON VIBE","CHOOSE YOUR VIBE"));Spacer(Modifier.height(8.dp))}
   items(GameMode.entries.size){index->val m=GameMode.entries[index];ModeCard(m,savedPlayerCount>=2||m==GameMode.RED_GREEN){onMode(m)};Spacer(Modifier.height(10.dp))}
  }
  item{Spacer(Modifier.height(20.dp))}
 }
}
@Composable private fun SectionLabel(t:String)=Text(t,color=VibeColors.TextSecondary,fontSize=11.sp,fontWeight=FontWeight.Black,letterSpacing=1.2.sp)
@Composable private fun RowScope.ChoiceChip(label:String,selected:Boolean,accent:Color,onClick:()->Unit){VibeActionSurface(onClick=onClick,modifier=Modifier.weight(1f),accent=accent,containerColor=if(selected)accent.copy(alpha=.24f) else MaterialTheme.colorScheme.surface,emphasized=selected,minHeight=48.dp){Box(Modifier.fillMaxWidth().padding(horizontal=8.dp,vertical=12.dp),contentAlignment=Alignment.Center){Text(label,color=VibeColors.TextPrimary,fontSize=12.sp,fontWeight=FontWeight.Black,maxLines=1)}}}
@Composable private fun PlayEntryCard(title:String,subtitle:String,icon:ImageVector,accent:Color,emphasized:Boolean,onClick:()->Unit){VibeActionSurface(onClick=onClick,modifier=Modifier.fillMaxWidth(),accent=accent,containerColor=if(emphasized)accent.copy(alpha=.18f) else MaterialTheme.colorScheme.surface,emphasized=emphasized){Row(Modifier.fillMaxWidth().padding(18.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(14.dp)){Box(Modifier.size(50.dp).background(accent.copy(alpha=.18f),CircleShape),contentAlignment=Alignment.Center){Icon(icon,null,tint=accent)};Column(Modifier.weight(1f)){Text(title,color=VibeColors.TextPrimary,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);Text(subtitle,color=VibeColors.TextSecondary,style=MaterialTheme.typography.bodyMedium)};Card(colors=CardDefaults.cardColors(containerColor=accent.copy(alpha=.18f)),shape=RoundedCornerShape(999.dp)){Text("→",color=accent,fontSize=22.sp,fontWeight=FontWeight.Black,modifier=Modifier.padding(horizontal=11.dp,vertical=4.dp))}}}}
@Composable private fun PremiumCard(isPremium:Boolean,ready:Boolean,price:String?,status:PurchaseStatus,onBuy:()->Unit){Card(colors=CardDefaults.cardColors(containerColor=VibeColors.PurpleBright.copy(alpha=.45f)),border=BorderStroke(1.dp,VibeColors.Purple.copy(alpha=.25f)),shape=RoundedCornerShape(24.dp),modifier=Modifier.fillMaxWidth()){Row(Modifier.fillMaxWidth().padding(15.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(12.dp)){Box(Modifier.size(44.dp).background(VibeColors.Purple.copy(alpha=.17f),CircleShape),contentAlignment=Alignment.Center){Icon(Icons.Default.Bolt,null,tint=VibeColors.Purple)};Column(Modifier.weight(1f)){Text(if(isPremium)AppLocale.pick("Premium actif","Premium active") else "VibeCheck Premium",color=VibeColors.TextPrimary,fontWeight=FontWeight.Bold);Text(if(isPremium)AppLocale.pick("Expérience sans publicité.","Ad-free experience.") else when(status){PurchaseStatus.PENDING->AppLocale.pick("Achat en attente.","Purchase pending.");PurchaseStatus.CANCELLED->AppLocale.pick("Achat annulé.","Purchase cancelled.");PurchaseStatus.ERROR->AppLocale.pick("Google Play indisponible.","Google Play unavailable.");PurchaseStatus.LOADING->AppLocale.pick("Connexion à Google Play…","Connecting to Google Play…");else->AppLocale.pick("Supprime les pubs définitivement.","Remove ads forever.")},color=VibeColors.TextSecondary,fontSize=12.sp)};if(!isPremium)Button(onClick=onBuy,enabled=ready&&status!=PurchaseStatus.PENDING&&status!=PurchaseStatus.LOADING,shape=RoundedCornerShape(16.dp),colors=ButtonDefaults.buttonColors(containerColor=VibeColors.Purple,contentColor=Color.White)){Text(if(status==PurchaseStatus.LOADING)"…" else price?:"Premium",fontWeight=FontWeight.Bold)}}}}
@Composable private fun ModeCard(mode:GameMode,express:Boolean,onClick:()->Unit){val v=modeVisual(mode);VibeActionSurface(onClick=onClick,modifier=Modifier.fillMaxWidth(),accent=v.accent,containerColor=v.accent.copy(alpha=.12f)){Row(Modifier.fillMaxWidth().padding(17.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(14.dp)){Box(Modifier.size(48.dp).background(v.accent.copy(alpha=.18f),CircleShape),contentAlignment=Alignment.Center){Icon(v.icon,null,tint=v.accent)};Column(Modifier.weight(1f)){Text(mode.title,color=VibeColors.TextPrimary,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);Text(if(express)AppLocale.pick("8 QUESTIONS • DÉMARRAGE DIRECT","8 QUESTIONS • QUICK START") else "8 QUESTIONS",color=v.accent,fontSize=10.sp,fontWeight=FontWeight.Black);Text(mode.subtitle,color=VibeColors.TextSecondary,fontSize=13.sp)};Text("→",color=v.accent,fontSize=24.sp,fontWeight=FontWeight.Black)}}}
private data class ModeVisual(val icon:ImageVector,val accent:Color);private fun modeVisual(m:GameMode)=when(m){GameMode.WHO_OF_US->ModeVisual(Icons.Default.Groups,VibeColors.Purple);GameMode.MOST_LIKELY->ModeVisual(Icons.Default.Whatshot,VibeColors.Orange);GameMode.RED_GREEN->ModeVisual(Icons.Default.Bolt,VibeColors.Green);GameMode.KNOWS_ME->ModeVisual(Icons.Default.Psychology,VibeColors.Blue)}
