package com.vibecheck.app.ui.screens
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.*
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.vibecheck.app.ui.theme.VibeColors
import com.vibecheck.app.ui.theme.VibeThemeStyle
import com.vibecheck.app.localization.AppLocale
@Composable fun SettingsScreen(selectedStyle:VibeThemeStyle,musicEnabled:Boolean=true,musicVolume:Float=.18f,onStyleSelected:(VibeThemeStyle)->Unit,onMusicEnabled:(Boolean)->Unit={},onMusicVolume:(Float)->Unit={},onBack:()->Unit){Column(Modifier.fillMaxSize()){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(AppLocale.pick("Réglages","Settings"),color=VibeColors.TextPrimary,style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black);Text(AppLocale.pick("Choisis l’ambiance de VibeCheck.","Choose VibeCheck’s look and feel."),color=VibeColors.TextSecondary)};TextButton(onClick=onBack){Text(AppLocale.pick("Retour","Back"),fontWeight=FontWeight.Bold)}};Spacer(Modifier.height(18.dp));LazyColumn(Modifier.fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Card(colors=CardDefaults.cardColors(containerColor=VibeColors.Blue.copy(alpha=.10f)),border=BorderStroke(1.dp,VibeColors.Blue.copy(alpha=.22f)),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(16.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(AppLocale.pick("Musique d’ambiance","Ambient music"),color=VibeColors.TextPrimary,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);Text(AppLocale.pick("Instrumentale douce, locale et optionnelle.","Gentle instrumental, local and optional."),color=VibeColors.TextSecondary)};Switch(checked=musicEnabled,onCheckedChange=onMusicEnabled,modifier=Modifier.semantics{contentDescription=AppLocale.pick("Musique d’ambiance","Ambient music")})};Spacer(Modifier.height(8.dp));Text(AppLocale.pick("Volume","Volume"),color=VibeColors.TextPrimary,fontWeight=FontWeight.Bold);Slider(value=musicVolume.coerceIn(0f,1f),onValueChange=onMusicVolume,enabled=musicEnabled,modifier=Modifier.fillMaxWidth().semantics{contentDescription=AppLocale.pick("Volume de la musique","Music volume")})}}};item{Card(colors=CardDefaults.cardColors(containerColor=VibeColors.Purple.copy(alpha=.12f)),border=BorderStroke(1.dp,VibeColors.Purple.copy(alpha=.22f)),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(16.dp)){Text(AppLocale.pick("Apparence","Appearance"),color=VibeColors.TextPrimary,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);Text(AppLocale.pick("Le thème pastel dessiné est l’identité VibeCheck par défaut. Tu peux changer d’ambiance ici.","The drawn pastel theme is VibeCheck’s default identity. You can switch styles here."),color=VibeColors.TextSecondary)}}};items(VibeThemeStyle.entries,key={it.id}){s->ThemePreviewCard(s,s==selectedStyle){onStyleSelected(s)}}}}}
@Composable private fun ThemePreviewCard(style:VibeThemeStyle,isSelected:Boolean,onClick:()->Unit){val preview=previewColors(style);Card(onClick=onClick,modifier=Modifier.fillMaxWidth().semantics{selected=isSelected;contentDescription=if(isSelected)AppLocale.pick("Thème ${style.label} sélectionné","Theme ${style.label} selected") else AppLocale.pick("Choisir le thème ${style.label}","Choose theme ${style.label}")},shape=RoundedCornerShape(26.dp),border=BorderStroke(if(isSelected)2.dp else 1.dp,if(isSelected)MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.surfaceVariant),colors=CardDefaults.cardColors(containerColor=if(isSelected)MaterialTheme.colorScheme.primary.copy(alpha=.08f) else MaterialTheme.colorScheme.surface),elevation=CardDefaults.cardElevation(defaultElevation=if(isSelected)3.dp else 1.dp)){Row(Modifier.fillMaxWidth().padding(16.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(14.dp)){Row(horizontalArrangement=Arrangement.spacedBy((-6).dp)){preview.forEachIndexed{i,c->Box(Modifier.size(if(i==0)36.dp else 30.dp).background(c,CircleShape))}};Column(Modifier.weight(1f)){Text(style.label,color=VibeColors.TextPrimary,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);Text(styleDescription(style),color=VibeColors.TextSecondary)};if(isSelected)Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.primary.copy(alpha=.15f)),shape=RoundedCornerShape(999.dp)){Text(AppLocale.pick("ACTIF","ACTIVE"),color=MaterialTheme.colorScheme.primary,fontWeight=FontWeight.Black,modifier=Modifier.padding(horizontal=10.dp,vertical=5.dp))}}}}
private fun previewColors(s:VibeThemeStyle)=when(s){VibeThemeStyle.PASTEL_DRAWN->listOf(Color(0xFFE8D7FF),Color(0xFFF7C9D9),Color(0xFFFFC8AD),Color(0xFFBFE5D0));VibeThemeStyle.PREMIUM_DARK->listOf(Color(0xFFC9A7FF),Color(0xFF95C8FF),Color(0xFF9BE6C1));VibeThemeStyle.KAWAII->listOf(Color(0xFFFFB8DF),Color(0xFFB9D9FF),Color(0xFFFFD39F));VibeThemeStyle.POP->listOf(Color(0xFFFFD44D),Color(0xFF70D7FF),Color(0xFFFF7A90));VibeThemeStyle.ELEGANT->listOf(Color(0xFFD8C29D),Color(0xFFB8B0A5),Color(0xFFE4D3B3));VibeThemeStyle.STREET->listOf(Color(0xFFB8FF3D),Color(0xFF7FE7D2),Color(0xFFFF9A3D));VibeThemeStyle.MINIMAL->listOf(Color(0xFFE7EAF0),Color(0xFFAEB7C5),Color(0xFFC8D0DC))}
private fun styleDescription(s:VibeThemeStyle)=when(s){VibeThemeStyle.PASTEL_DRAWN->AppLocale.pick("Lavande, rose poudré, pêche, menthe et crème","Lavender, dusty pink, peach, mint and cream");VibeThemeStyle.PREMIUM_DARK->AppLocale.pick("Profond, violet et cinématique","Deep, purple and cinematic");VibeThemeStyle.KAWAII->AppLocale.pick("Rose pastel, doux et lumineux","Soft, bright pastel pink");VibeThemeStyle.POP->AppLocale.pick("Énergique, contrasté et coloré","Energetic, bold and colorful");VibeThemeStyle.ELEGANT->AppLocale.pick("Sobre, chaud et raffiné","Warm, understated and refined");VibeThemeStyle.STREET->AppLocale.pick("Urbain, acide et percutant","Urban, sharp and punchy");VibeThemeStyle.MINIMAL->AppLocale.pick("Neutre, net et concentré","Neutral, clean and focused")}
