package com.vibecheck.app.ui.state

import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import com.vibecheck.app.domain.*
import com.vibecheck.app.domain.model.*
import com.vibecheck.app.domain.solo.PersonaAnswer

enum class AppScreen { HOME, PLAYERS, GAME, RESULT, LEADERBOARD }
class GameViewModel(private val savedStateHandle:SavedStateHandle):ViewModel(){
 val screenName=savedStateHandle.getStateFlow(KEY_SCREEN,AppScreen.HOME.name);val modeName=savedStateHandle.getStateFlow(KEY_MODE,GameMode.WHO_OF_US.name);val questionIndex=savedStateHandle.getStateFlow(KEY_QUESTION_INDEX,0);val savedVotes=savedStateHandle.getStateFlow(KEY_VOTES,arrayListOf<String>());val players=savedStateHandle.getStateFlow(KEY_PLAYERS,arrayListOf<String>());val challengeTarget=savedStateHandle.getStateFlow(KEY_CHALLENGE_TARGET,NO_CHALLENGE);val sessionSeed=savedStateHandle.getStateFlow(KEY_SESSION_SEED,System.currentTimeMillis());val sessionInstanceId=savedStateHandle.getStateFlow(KEY_SESSION_INSTANCE_ID,System.nanoTime());val intensityName=savedStateHandle.getStateFlow(KEY_INTENSITY,GameIntensity.NORMAL.name);val packName=savedStateHandle.getStateFlow(KEY_PACK,GamePack.MIX.name);val legacyChallenge=savedStateHandle.getStateFlow(KEY_LEGACY_CHALLENGE,false);val knowSecretAnswer=savedStateHandle.getStateFlow(KEY_KNOW_SECRET,"");val knowGuesserIndex=savedStateHandle.getStateFlow(KEY_KNOW_GUESSER_INDEX,0);val knowScores=savedStateHandle.getStateFlow(KEY_KNOW_SCORES,arrayListOf<Int>());val knowHandoffPending=savedStateHandle.getStateFlow(KEY_KNOW_HANDOFF,false);val isSoloSession=savedStateHandle.getStateFlow(KEY_IS_SOLO_SESSION,false);val soloPersonaIds=savedStateHandle.getStateFlow(KEY_SOLO_PERSONA_IDS,arrayListOf<String>());val soloPlayerName=savedStateHandle.getStateFlow(KEY_SOLO_PLAYER_NAME,"Moi");val soloPlayerAnswer=savedStateHandle.getStateFlow(KEY_SOLO_PLAYER_ANSWER,"")
 fun acceptChallenge(c:Challenge){clearSoloSession();savedStateHandle[KEY_MODE]=c.mode.name;savedStateHandle[KEY_CHALLENGE_TARGET]=c.targetPercent;savedStateHandle[KEY_QUESTION_INDEX]=0;savedStateHandle[KEY_VOTES]=arrayListOf<String>();savedStateHandle[KEY_SESSION_SEED]=c.seed;savedStateHandle[KEY_SESSION_INSTANCE_ID]=System.nanoTime();savedStateHandle[KEY_INTENSITY]=(c.intensity?:GameIntensity.NORMAL).name;savedStateHandle[KEY_PACK]=(c.pack?:GamePack.MIX).name;savedStateHandle[KEY_LEGACY_CHALLENGE]=c.intensity==null;resetKnowMeState();savedStateHandle[KEY_SCREEN]=initialScreenFor(c.mode).name}
 fun selectMode(m:GameMode){clearSoloSession();savedStateHandle[KEY_MODE]=m.name;savedStateHandle[KEY_CHALLENGE_TARGET]=NO_CHALLENGE;savedStateHandle[KEY_QUESTION_INDEX]=0;savedStateHandle[KEY_VOTES]=arrayListOf<String>();resetKnowMeState();savedStateHandle[KEY_SCREEN]=initialScreenFor(m).name}
 fun quickStartMode(m:GameMode){selectMode(m);if(m==GameMode.RED_GREEN||PlayerRules.canStart(players.value)){savedStateHandle[KEY_SESSION_SEED]=System.currentTimeMillis();savedStateHandle[KEY_SESSION_INSTANCE_ID]=System.nanoTime();savedStateHandle[KEY_SCREEN]=AppScreen.GAME.name}}
 fun openLeaderboard(){savedStateHandle[KEY_SCREEN]=AppScreen.LEADERBOARD.name};fun editPlayers(){clearSoloSession();savedStateHandle[KEY_SCREEN]=AppScreen.PLAYERS.name};fun selectIntensity(v:GameIntensity){if(challengeTarget.value==NO_CHALLENGE)savedStateHandle[KEY_INTENSITY]=v.name};fun selectPack(v:GamePack){if(challengeTarget.value==NO_CHALLENGE)savedStateHandle[KEY_PACK]=v.name};fun restorePlayers(v:List<String>){if(players.value.isEmpty())savedStateHandle[KEY_PLAYERS]=ArrayList(v)};fun addPlayer(v:String){savedStateHandle[KEY_PLAYERS]=ArrayList(players.value+v)};fun removePlayer(v:String){savedStateHandle[KEY_PLAYERS]=ArrayList(players.value.filterNot{it==v})}
 fun goBackHome(){goHome()};fun startGame(){clearSoloSession();resetRound();savedStateHandle[KEY_SESSION_SEED]=System.currentTimeMillis();savedStateHandle[KEY_SCREEN]=AppScreen.GAME.name}
 fun startSoloSession(personaIds:List<String>,mode:GameMode=GameMode.WHO_OF_US,seed:Long=System.currentTimeMillis(),playerName:String="Moi"){val ids=personaIds.filter{it.isNotBlank()}.distinct();if(ids.size !in 2..7||mode==GameMode.KNOWS_ME)return;savedStateHandle[KEY_IS_SOLO_SESSION]=true;savedStateHandle[KEY_SOLO_PERSONA_IDS]=ArrayList(ids);savedStateHandle[KEY_SOLO_PLAYER_NAME]=playerName.trim().ifBlank{"Moi"};savedStateHandle[KEY_SOLO_PLAYER_ANSWER]="";savedStateHandle[KEY_MODE]=mode.name;savedStateHandle[KEY_CHALLENGE_TARGET]=NO_CHALLENGE;resetRound();savedStateHandle[KEY_SESSION_SEED]=seed;savedStateHandle[KEY_SCREEN]=AppScreen.GAME.name}
 fun submitSoloPlayerAnswer(answer:String){if(!isSoloSession.value||screenName.value!=AppScreen.GAME.name||answer.isBlank())return;savedStateHandle[KEY_SOLO_PLAYER_ANSWER]=answer}
 fun submitSoloRound(questionId:String,answers:List<PersonaAnswer>,isLastQuestion:Boolean){if(!isSoloSession.value||soloPlayerAnswer.value.isBlank()||answers.isEmpty())return;val current=SessionCodec.decodeVotes(savedVotes.value);if(current.any{it.questionId==questionId})return;val allOptions=answers.map{it.option}+soloPlayerAnswer.value;val majority=allOptions.groupingBy{it}.eachCount().entries.sortedWith(compareByDescending<Map.Entry<String,Int>>{it.value}.thenBy{it.key}).first().key;savedStateHandle[KEY_SOLO_PLAYER_ANSWER]="";answer(questionId,majority,isLastQuestion)}
 fun answer(questionId:String,answer:String,isLastQuestion:Boolean){if(screenName.value==AppScreen.RESULT.name)return;val c=SessionCodec.decodeVotes(savedVotes.value);if(c.any{it.questionId==questionId})return;savedStateHandle[KEY_VOTES]=ArrayList(SessionCodec.encodeVotes(c+Vote(questionId,answer)));if(isLastQuestion)savedStateHandle[KEY_SCREEN]=AppScreen.RESULT.name else savedStateHandle[KEY_QUESTION_INDEX]=questionIndex.value+1}
 fun setKnowMeSecret(a:String){if(modeName.value==GameMode.KNOWS_ME.name&&a.isNotBlank()&&knowSecretAnswer.value.isBlank()){savedStateHandle[KEY_KNOW_SECRET]=a;savedStateHandle[KEY_KNOW_GUESSER_INDEX]=0;savedStateHandle[KEY_KNOW_HANDOFF]=true;ensureKnowScoreSlots()}}
 fun submitKnowMeGuess(a:String,isLastQuestion:Boolean){if(modeName.value!=GameMode.KNOWS_ME.name||screenName.value==AppScreen.RESULT.name)return;val secret=knowSecretAnswer.value;val guessers=players.value.drop(1);if(secret.isBlank()||guessers.isEmpty())return;ensureKnowScoreSlots();val i=knowGuesserIndex.value.coerceIn(0,guessers.lastIndex);val scores=ArrayList(knowScores.value);if(a==secret)scores[i]++;savedStateHandle[KEY_KNOW_SCORES]=scores;if(i<guessers.lastIndex){savedStateHandle[KEY_KNOW_GUESSER_INDEX]=i+1;savedStateHandle[KEY_KNOW_HANDOFF]=true}else if(isLastQuestion)savedStateHandle[KEY_SCREEN]=AppScreen.RESULT.name else{savedStateHandle[KEY_QUESTION_INDEX]=questionIndex.value+1;savedStateHandle[KEY_KNOW_SECRET]="";savedStateHandle[KEY_KNOW_GUESSER_INDEX]=0;savedStateHandle[KEY_KNOW_HANDOFF]=true}}
 fun confirmKnowMeHandoff(){savedStateHandle[KEY_KNOW_HANDOFF]=false};fun abandonGame(){goHome()};fun replay(){savedStateHandle[KEY_VOTES]=arrayListOf<String>();savedStateHandle[KEY_QUESTION_INDEX]=0;savedStateHandle[KEY_SOLO_PLAYER_ANSWER]="";resetKnowMeState();savedStateHandle[KEY_SESSION_SEED]=System.currentTimeMillis();savedStateHandle[KEY_SESSION_INSTANCE_ID]=System.nanoTime();savedStateHandle[KEY_SCREEN]=AppScreen.GAME.name};fun goHome(){clearSoloSession();resetRound();resetKnowMeState();savedStateHandle[KEY_CHALLENGE_TARGET]=NO_CHALLENGE;savedStateHandle[KEY_SCREEN]=AppScreen.HOME.name}
 private fun resetRound(){savedStateHandle[KEY_VOTES]=arrayListOf<String>();savedStateHandle[KEY_QUESTION_INDEX]=0;savedStateHandle[KEY_SESSION_INSTANCE_ID]=System.nanoTime()};private fun ensureKnowScoreSlots(){val n=players.value.drop(1).size;if(knowScores.value.size!=n)savedStateHandle[KEY_KNOW_SCORES]=ArrayList(List(n){0})};private fun clearSoloSession(){savedStateHandle[KEY_IS_SOLO_SESSION]=false;savedStateHandle[KEY_SOLO_PERSONA_IDS]=arrayListOf<String>();savedStateHandle[KEY_SOLO_PLAYER_ANSWER]=""};private fun resetKnowMeState(){savedStateHandle[KEY_KNOW_SECRET]="";savedStateHandle[KEY_KNOW_GUESSER_INDEX]=0;savedStateHandle[KEY_KNOW_SCORES]=arrayListOf<Int>();savedStateHandle[KEY_KNOW_HANDOFF]=false};private fun initialScreenFor(m:GameMode)=if(m==GameMode.RED_GREEN)AppScreen.GAME else AppScreen.PLAYERS
 companion object{const val NO_CHALLENGE=-1;private const val KEY_SCREEN="screen";private const val KEY_MODE="mode";private const val KEY_QUESTION_INDEX="question_index";private const val KEY_VOTES="votes";private const val KEY_PLAYERS="players";private const val KEY_CHALLENGE_TARGET="challenge_target";private const val KEY_SESSION_SEED="session_seed";private const val KEY_SESSION_INSTANCE_ID="session_instance_id";private const val KEY_INTENSITY="intensity";private const val KEY_PACK="pack";private const val KEY_LEGACY_CHALLENGE="legacy_challenge";private const val KEY_KNOW_SECRET="know_secret";private const val KEY_KNOW_GUESSER_INDEX="know_guesser_index";private const val KEY_KNOW_SCORES="know_scores";private const val KEY_KNOW_HANDOFF="know_handoff";private const val KEY_IS_SOLO_SESSION="is_solo_session";private const val KEY_SOLO_PERSONA_IDS="solo_persona_ids";private const val KEY_SOLO_PLAYER_NAME="solo_player_name";private const val KEY_SOLO_PLAYER_ANSWER="solo_player_answer"}
}
